### ISSUE TITLE
Can LGT-92 set to SF12?

### ISSUE THREAD

**Issue by yudha2putra** [dragino/LGT-92_-LoRa_GPS_Tracker#1]
I have set LGT-92 using AT+DR=0 until AT+DR=5 when transmit data to Lorawan Gateway, but there is no data is transmited using SF12, is only can transmit using SF7-SF10. Is it posible to using SF12 when transmit data? I'm using kerlink station Gateway and TTN Server. Thanks

**Comment by dragino** [comment]
This depends on the frequency band. US915 version doesn't support SF12 yet. When we update the code to LoRaWAN v1.0.3 we will support.
