### ISSUE TITLE
GPS is not receiving after compiling the source code

### ISSUE THREAD

**Issue by conure44** [dragino/LGT-92_-LoRa_GPS_Tracker#2]
When we use the firmware 1.4 provided everything is working except the packages timing are not consistent with the time we chose.
So we re-complied the source code without changing anything. After compiling the code, we are getting consistent payload but now we are not getting GPS. Light is blinking red. 
Is the firmware V1.4 generated from this source code ? If yes why we have different behavior between V1.4 firmware and the hex generated from compiling the source code ? How could we solve the issue of not receiving GPS after compiling the source code ?

**Comment by dragino** [comment]
In this code. A new feature AT+GPST is introduce. this will set the fix time. If AT+GPST=0 means disable gps fix. AT+FDR will set this value to 0 so problem happen. In next update, we will fix this by set AT+GPST=150 by default.
