### ISSUE TITLE
1.6.7 reports version as 1.6.4

### ISSUE THREAD

**Issue by marcelstoer** [dragino/LGT-92_-LoRa_GPS_Tracker#28]
The firmware from https://www.dragino.com/downloads/index.php?dir=LGT_92/firmware/v1.6.7/ reports its version as 1.6.4 in the LoRaWAN message.

The decoder/payload formatter is defined as using `var Firmware = 160 + (bytes[10] & 0x1f)` to decode the version. With byte 11 being 0x64 (e.g. as in `02 D4 3C 64 00 88 A1 00 4D DC 64`) this means 160 + 4 => 1.6.4. instead of 1.6.7.

https://github.com/dragino/LGT-92_-LoRa_GPS_Tracker/blob/4800dc2451745dd020654f8391c94a405ac24eac/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/lora.c#L122

has the correct version. So, I don't really understand what's going wrong here.

The version reported on UART is correct

```
LSI=37024
LGT-92 Device
Image Version: v1.6.7
LoRaWan Stack: DR-LWS-005
```

**Comment by tormodvolden** [comment]
Only the last "digit"or minor version is included in the LoRaWAN transmission, and this number is defined separately in the code (and is not always up to date). The parsing script on the receiving side prepends the "1.6." part.

**Comment by tormodvolden** [comment]
See also #16
