### ISSUE TITLE
AT+NMEA Return an ERROR

### ISSUE THREAD

**Issue by tmsd2001** [dragino/LGT-92_-LoRa_GPS_Tracker#32]
The LGT-92 Firmware is 1.6.5.
AT+NMEA886=? is working.
Every AT+NMEA886 or AT+NMEA353 set command returns AT_PARAM_ERROR.
Do I have the wrong formatting?
I send this format "AT+NMEA886=2"
The manual says the default value is 0, but I receive 1?
A downlink via TTN does not change the values as desired.
Downlink FPort 1 Bytes "AB 05" switch to "NMEA886=2" and "AB 04" to "NMEA886=11"

**Comment by dragino** [comment]
Due to IC Shortage, a batch of LGT92 use ublox Chip which doesn't support this command.
